# Generated by Django 5.0.7 on 2024-08-16 06:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_date', models.DateField()),
                ('follow_up_date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('reference', models.CharField(choices=[('Amazon', 'Amazon'), ('Flipkart', 'Flipkart'), ('India Mart', 'India Mart'), ('Alibaba', 'Alibaba')], max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('In Progress', 'In Progress')], max_length=255)),
            ],
            options={
                'db_table': 'sales_order',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complaint_id', models.CharField(max_length=50)),
                ('complaint_date', models.DateField()),
                ('customer_type', models.CharField(choices=[('type1', 'type1'), ('type2', 'type2'), ('type3', 'type3'), ('type4', 'type4'), ('type5', 'type5')], max_length=50)),
                ('complaint_type', models.CharField(choices=[('choice1', 'choice1'), ('choice2', 'choice2'), ('choice3', 'choice3'), ('choice4', 'choice4'), ('choice5', 'choice5')], max_length=50)),
                ('is_resolve', models.BooleanField(default=False)),
                ('token', models.DateTimeField(blank=True, null=True)),
                ('token_number', models.CharField(blank=True, max_length=50, null=True)),
                ('machine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_model', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_no', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online'), ('Not Paid', 'Not Paid')], max_length=50)),
                ('collected_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('ticket_status', models.CharField(choices=[('Not Registered', 'Not Registered'), ('Pending', 'Pending'), ('Send to Billing', 'Send to Billing'), ('Resolved', 'Resolved')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.technician')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_executive', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.salesorder')),
            ],
            options={
                'db_table': 'billing_item',
            },
        ),
    ]
