# Generated by Django 5.0.7 on 2024-09-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_complaint_complaint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid'), ('Cancelled', 'Cancelled'), ('Free', 'Free')], max_length=50),
        ),
    ]
