# Generated by Django 5.0.7 on 2024-08-16 06:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('terms_and_conditions', models.TextField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=50)),
                ('phone', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('terms_and_conditions', models.TextField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.TextField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('terms_and_conditions', models.TextField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'technician',
            },
        ),
    ]
