# Generated by Django 5.0.7 on 2024-08-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintbilling',
            name='quantity',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='complaintbilling',
            name='rate',
            field=models.TextField(max_length=100),
        ),
    ]
