# Generated by Django 5.0.7 on 2024-08-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technician', '0002_alter_complaintbilling_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintbilling',
            name='rate',
            field=models.FloatField(max_length=100),
        ),
    ]
